import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  filters: { marginBottom: 16 },
  filterLabel: { fontSize: 14, fontWeight: 'bold', marginBottom: 8, marginTop: 8 },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
  filterButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, backgroundColor: '#f0f0f0' },
  activeFilter: { backgroundColor: '#007AFF' },
  filterText: { fontSize: 12, color: '#666', textTransform: 'capitalize' },
  activeFilterText: { color: 'white' },
  disputeList: { flex: 1 },
  disputeCard: { flexDirection: 'row', backgroundColor: 'white', padding: 16, marginBottom: 8, borderRadius: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  disputeInfo: { flex: 1 },
  disputeHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  typeBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  typeBadgeText: { color: 'white', fontSize: 12, fontWeight: 'bold', textTransform: 'uppercase' },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  statusBadgeText: { color: 'white', fontSize: 12, fontWeight: 'bold', textTransform: 'capitalize' },
  disputeDescription: { fontSize: 14, color: '#333', marginBottom: 8 },
  disputeDetails: { gap: 4 },
  disputeDate: { fontSize: 12, color: '#666' },
  disputeActions: { justifyContent: 'center', alignItems: 'center' },
  actionButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16 },
  resolveButton: { backgroundColor: '#28A745' },
  actionButtonText: { color: 'white', fontSize: 12, fontWeight: 'bold' },
  actionModal: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: 'white', padding: 20, borderRadius: 12, width: '90%', maxWidth: 400 },
  modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 16, textAlign: 'center' },
  claimDetails: { fontSize: 16, fontWeight: '600', color: '#1f2937', marginBottom: 12, textAlign: 'center' },
  notesInput: { borderWidth: 1, borderColor: '#ddd', borderRadius: 8, padding: 12, height: 80, textAlignVertical: 'top', marginBottom: 16 },
  modalActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'center' },
  modalButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, minWidth: 80 },
  escalateButton: { backgroundColor: '#FFA500' },
  refundButton: { backgroundColor: '#DC3545' },
  cancelButton: { backgroundColor: '#666' },
  modalButtonText: { color: 'white', fontSize: 14, fontWeight: 'bold', textAlign: 'center' }
});