import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f9fafb' },
  header: { padding: 20, backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { fontSize: 20, fontWeight: 'bold', color: '#1f2937', flex: 1 },
  subtitle: { fontSize: 14, color: '#6b7280' },
  backButton: { backgroundColor: '#f3f4f6', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  backButtonText: { color: '#374151', fontSize: 14, fontWeight: '500' },
  addMilestoneButton: { backgroundColor: '#3b82f6', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  addMilestoneButtonText: { color: 'white', fontSize: 14, fontWeight: '600' },
  stats: { flexDirection: 'row', backgroundColor: 'white', paddingVertical: 15, paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  statItem: { flex: 1, alignItems: 'center' },
  statNumber: { fontSize: 18, fontWeight: 'bold', color: '#1f2937', marginBottom: 2 },
  statLabel: { fontSize: 12, color: '#6b7280' },
  controls: { flexDirection: 'row', padding: 15, gap: 10 },
  calendarViewToggle: { flex: 1, backgroundColor: '#8b5cf6', padding: 12, borderRadius: 8, alignItems: 'center' },
  calendarViewToggleText: { color: 'white', fontSize: 14, fontWeight: '600' },
  bimViewerToggle: { flex: 1, backgroundColor: '#3b82f6', padding: 12, borderRadius: 8, alignItems: 'center' },
  bimViewerToggleText: { color: 'white', fontSize: 14, fontWeight: '600' },
  heatmapToggle: { flex: 1, backgroundColor: '#f3f4f6', padding: 12, borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: '#e5e7eb' },
  heatmapToggleActive: { backgroundColor: '#dc2626', borderColor: '#dc2626' },
  heatmapToggleText: { color: '#374151', fontSize: 14, fontWeight: '600' },
  heatmapToggleTextActive: { color: 'white' },
  bimViewerContainer: { height: 300, backgroundColor: 'white', marginHorizontal: 15, marginBottom: 15, borderRadius: 10, borderWidth: 1, borderColor: '#e5e7eb' },
  content: { flex: 1 },
  conceptSection: { backgroundColor: 'white', marginHorizontal: 15, marginBottom: 10, borderRadius: 10, borderWidth: 1, borderColor: '#e5e7eb' },
  conceptHeader: { flexDirection: 'row', alignItems: 'center', padding: 15, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  conceptInfo: { flex: 1 },
  conceptName: { fontSize: 16, fontWeight: 'bold', color: '#1f2937', marginBottom: 2 },
  conceptStats: { fontSize: 12, color: '#6b7280' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  forecastButton: { backgroundColor: '#3b82f6', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  forecastButtonText: { color: 'white', fontSize: 12, fontWeight: '600' },
  expandIcon: { fontSize: 16, color: '#6b7280' },
  conceptLogs: { padding: 15 },
  emptyLogs: { alignItems: 'center', paddingVertical: 20 },
  emptyText: { fontSize: 14, color: '#9ca3af' },
  logContainer: { marginBottom: 15 },
  viewBIMButton: { backgroundColor: '#f3f4f6', padding: 8, borderRadius: 6, alignItems: 'center', marginTop: 8 },
  viewBIMButtonText: { fontSize: 12, color: '#374151', fontWeight: '500' }
});