const styles = StyleSheet.create({
  container: { backgroundColor: 'white', borderRadius: 8, padding: 15, marginVertical: 10 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  title: { fontSize: 16, fontWeight: 'bold' },
  filterButton: { backgroundColor: '#2563eb', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  filterText: { color: 'white', fontSize: 12, fontWeight: '500' },
  legend: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 15 },
  legendItem: { flexDirection: 'row', alignItems: 'center' },
  legendColor: { width: 12, height: 12, borderRadius: 6, marginRight: 5 },
  legendText: { fontSize: 10, color: '#6b7280' },
  weekHeader: { flexDirection: 'row', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  nameColumn: { width: 80, fontSize: 12, fontWeight: 'bold', color: '#374151' },
  dayColumn: { flex: 1, alignItems: 'center' },
  dayText: { fontSize: 10, color: '#6b7280' },
  dateText: { fontSize: 12, fontWeight: 'bold', marginTop: 2 },
  heatmapContainer: { maxHeight: 300 },
  chiefRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  chiefName: { width: 80, paddingRight: 8 },
  chiefNameText: { fontSize: 11, fontWeight: '500', color: '#374151' },
  availableBadge: { backgroundColor: '#dcfce7', paddingHorizontal: 4, paddingVertical: 1, borderRadius: 4, marginTop: 2 },
  availableBadgeText: { fontSize: 8, color: '#16a34a', fontWeight: 'bold' },
  availabilityCell: { flex: 1, height: 24, marginHorizontal: 1, borderRadius: 4, alignItems: 'center', justifyContent: 'center' },
  todayCell: { borderWidth: 2, borderColor: '#2563eb' },
  noteIndicator: { fontSize: 8 },
  loadingText: { textAlign: 'center', color: '#6b7280', padding: 20 },
  emptyState: { padding: 20, alignItems: 'center' },
  emptyText: { color: '#6b7280', fontSize: 14, textAlign: 'center' }
});