import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 20, paddingBottom: 10, backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  title: { fontSize: 24, fontWeight: 'bold', color: '#dc2626' },
  tabContainer: { backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  tab: { backgroundColor: '#f8fafc', paddingHorizontal: 16, paddingVertical: 12, borderRadius: 5, marginRight: 8, marginVertical: 8 },
  activeTab: { backgroundColor: '#dc2626' },
  tabText: { color: '#6b7280', fontWeight: '500', fontSize: 14 },
  activeTabText: { color: 'white' },
  content: { flex: 1, backgroundColor: '#f8fafc' },
  tabContent: { padding: 20, backgroundColor: '#f8fafc', minHeight: 400 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', marginVertical: 15, color: '#374151' },
  equipmentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  buttonGroup: { flexDirection: 'row', gap: 8 },
  addButton: { backgroundColor: '#dc2626', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 8 },
  addButtonText: { color: 'white', fontWeight: '600', fontSize: 14 },
  offlineButton: { backgroundColor: '#0ea5e9', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 8 },
  offlineButtonText: { color: 'white', fontWeight: '600', fontSize: 14 },
  equipmentCard: { backgroundColor: 'white', padding: 15, borderRadius: 10, marginBottom: 10, elevation: 2 },
  equipmentInfo: { flex: 1 },
  equipmentName: { fontSize: 16, fontWeight: 'bold', color: '#1e293b' },
  equipmentDetails: { fontSize: 14, color: '#6b7280', marginBottom: 4 },
  equipmentRate: { fontSize: 16, fontWeight: '600', color: '#059669', marginBottom: 4 },
  equipmentDescription: { fontSize: 14, color: '#6b7280' },
  unverifiedSection: { alignItems: 'flex-end' },
  unverifiedBadge: { backgroundColor: '#fef3c7', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, marginBottom: 8 },
  unverifiedText: { fontSize: 12, color: '#92400e', fontWeight: '500' },
  claimButton: { backgroundColor: '#0ea5e9', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  claimButtonText: { color: 'white', fontSize: 12, fontWeight: '500' },
  profileContainer: { backgroundColor: 'white', padding: 16, borderRadius: 10, margin: 4 },
  statsContainer: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 16 },
  statItem: { alignItems: 'center', flex: 1 },
  statLabel: { fontSize: 12, color: '#6b7280', marginBottom: 4 },
  statValue: { fontSize: 16, fontWeight: 'bold', color: '#374151' },
  leaderboardButton: { backgroundColor: '#dc2626', padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 16 },
  leaderboardButtonText: { color: 'white', fontWeight: '600', fontSize: 16 },
  loadingText: { textAlign: 'center', color: '#6b7280', fontSize: 16, marginTop: 20 },
  defaultText: { textAlign: 'center', color: '#6b7280', fontSize: 16, marginTop: 20 }
});